### ISSUE TITLE
Delete Account from Settings

### ISSUE THREAD

**Issue by Kanav-Arora** [Kanav-Arora/TravelBuddy#99]
In settings page, delete Modal button click will delete the user by setting status to inactive/deleted and on successful call will redirect to home page and set the Auth states to null.

**Comment by BautiSobenko** [comment]
Hey Kanav! I'm working on the solution. In these days i'll upload my pull request :)

**Comment by BautiSobenko** [comment]
When a user clicks on the "delete user" button and this user signs in again with his email, it should appear as if he is not registered in the database (this does not happen).

When the user signs-in we should check that the email exists in the database and also that the status is active. Therefore when the user signs-up again, after deleting his account we just set his status to active since it already exists in the database.

I can change this if you give me the ok! 👍

**Comment by Kanav-Arora** [comment]
Hi @BautiSobenko 
Thanks for showing interest and reporting this issue. 

Yes you are totally right. On deleting status should be set to `deleted`.
On signing up  if the document already exists in `User` collection and if the status is deleted we should delete the document and create a new one. Currently we are on handling this case ig.

On signing in if the user exists but the status is `deleted`, we give account doesn't exists error. For that you need to change signinUser controller. 

Ping me if you want to discuss something.

**Comment by Kanav-Arora** [comment]
For testing you can fork the postman collection

**Comment by BautiSobenko** [comment]
Great! I'll get on with that in a while. Thank you.
